export { default as IconFav } from './IconFav'
export { default as IconHistory } from './IconHistory'
export { default as IconSearch } from './IconSearch'
export { default as IconX } from './IconX'
export { default as LogoWhite } from './LogoWhite'